version: '3.1'
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: redditdailysoup
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
